# Homework #3

# Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from 06-environment.md.

In [1]:
import numpy as np
import pandas as pd

# Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [3]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [4]:
data = data[['MSRP','Make', 'Model',  'Year', 'Engine HP','Engine Cylinders','Transmission Type',
'Vehicle Style','highway MPG','city mpg']]

In [5]:
data.columns = data.columns.str.replace(' ', '_').str.lower()

In [6]:
data

msrp     make       model  year  engine_hp  engine_cylinders  \
0      46135      BMW  1 Series M  2011      335.0               6.0   
1      40650      BMW    1 Series  2011      300.0               6.0   
2      36350      BMW    1 Series  2011      300.0               6.0   
3      29450      BMW    1 Series  2011      230.0               6.0   
4      34500      BMW    1 Series  2011      230.0               6.0   
...      ...      ...         ...   ...        ...               ...   
11909  46120    Acura         ZDX  2012      300.0               6.0   
11910  56670    Acura         ZDX  2012      300.0               6.0   
11911  50620    Acura         ZDX  2012      300.0               6.0   
11912  50920    Acura         ZDX  2013      300.0               6.0   
11913  28995  Lincoln      Zephyr  2006      221.0               6.0   

      transmission_type  vehicle_style  highway_mpg  city_mpg  
0                MANUAL          Coupe           26        19  
1                MANUAL    Convertible           28        19  
2                MANUAL          Coupe           28        20  
3                MANUAL          Coupe           28        18  
4                MANUAL    Convertible           28        18  
...                 ...            ...          ...       ...  
11909         AUTOMATIC  4dr Hatchback           23        16  
11910         AUTOMATIC  4dr Hatchback           23        16  
11911         AUTOMATIC  4dr Hatchback           23        16  
11912         AUTOMATIC  4dr Hatchback           23        16  
11913         AUTOMATIC          Sedan           26        17  

[11914 rows x 10 columns]

In [7]:
data.isnull().sum()

msrp                  0
make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
dtype: int64

In [8]:
data = data.fillna(0)

In [9]:
data.isnull().sum()

msrp                 0
make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
dtype: int64

In [10]:
data.rename(columns={'msrp':'price'}, inplace=True)

In [11]:
data

price     make       model  year  engine_hp  engine_cylinders  \
0      46135      BMW  1 Series M  2011      335.0               6.0   
1      40650      BMW    1 Series  2011      300.0               6.0   
2      36350      BMW    1 Series  2011      300.0               6.0   
3      29450      BMW    1 Series  2011      230.0               6.0   
4      34500      BMW    1 Series  2011      230.0               6.0   
...      ...      ...         ...   ...        ...               ...   
11909  46120    Acura         ZDX  2012      300.0               6.0   
11910  56670    Acura         ZDX  2012      300.0               6.0   
11911  50620    Acura         ZDX  2012      300.0               6.0   
11912  50920    Acura         ZDX  2013      300.0               6.0   
11913  28995  Lincoln      Zephyr  2006      221.0               6.0   

      transmission_type  vehicle_style  highway_mpg  city_mpg  
0                MANUAL          Coupe           26        19  
1                MANUAL    Convertible           28        19  
2                MANUAL          Coupe           28        20  
3                MANUAL          Coupe           28        18  
4                MANUAL    Convertible           28        18  
...                 ...            ...          ...       ...  
11909         AUTOMATIC  4dr Hatchback           23        16  
11910         AUTOMATIC  4dr Hatchback           23        16  
11911         AUTOMATIC  4dr Hatchback           23        16  
11912         AUTOMATIC  4dr Hatchback           23        16  
11913         AUTOMATIC          Sedan           26        17  

[11914 rows x 10 columns]

# Question 1
What is the most frequent observation (mode) for the column transmission_type?

In [12]:
data.transmission_type.mode()

0    AUTOMATIC
Name: transmission_type, dtype: object

# Question 2
Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features in the dataset.

What are the two features that have the biggest correlation in this dataset?

In [13]:
data.dtypes

price                  int64
make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
dtype: object

In [14]:
data.nunique()

price                6049
make                   48
model                 915
year                   28
engine_hp             357
engine_cylinders        9
transmission_type       5
vehicle_style          16
highway_mpg            59
city_mpg               69
dtype: int64

In [15]:
data.columns

Index(['price', 'make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'highway_mpg', 'city_mpg'],
      dtype='object')

In [16]:
numerical = ['price','year', 'engine_hp', 'engine_cylinders','highway_mpg', 'city_mpg']

In [17]:
categorical = ['make', 'model', 'transmission_type', 'vehicle_style']

In [18]:
data[numerical].corr().style.background_gradient(cmap='coolwarm').set_precision(2)

C:\Users\POLOO2\AppData\Local\Temp\ipykernel_9456\713168363.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  data[numerical].corr().style.background_gradient(cmap='coolwarm').set_precision(2)


engine_hp and year 0.34
engine_hp and engine_cylinders 0.77
highway_mpg and engine_cylinders -0.61
highway_mpg and city_mpg 0.89

highway_mpg and city_mpg 0.89

# Make price binary
Now we need to turn the price variable from numeric into a binary format.
Let's create a variable above_average which is 1 if the price is above its mean value and 0 otherwise.

In [19]:
average = data['price'].mean()
average

40594.737032063116

In [20]:
data.rename(columns={'price':'above_average'}, inplace=True)

In [21]:
(data.above_average > average).head

<bound method NDFrame.head of 0         True
1         True
2        False
3        False
4        False
         ...  
11909     True
11910     True
11911     True
11912     True
11913    False
Name: above_average, Length: 11914, dtype: bool>

In [22]:
data.above_average = (data.above_average > average).astype(int)

In [23]:
data.above_average.head

<bound method NDFrame.head of 0        1
1        1
2        0
3        0
4        0
        ..
11909    1
11910    1
11911    1
11912    1
11913    0
Name: above_average, Length: 11914, dtype: int32>

In [24]:
data.head()

above_average make       model  year  engine_hp  engine_cylinders  \
0              1  BMW  1 Series M  2011      335.0               6.0   
1              1  BMW    1 Series  2011      300.0               6.0   
2              0  BMW    1 Series  2011      300.0               6.0   
3              0  BMW    1 Series  2011      230.0               6.0   
4              0  BMW    1 Series  2011      230.0               6.0   

  transmission_type vehicle_style  highway_mpg  city_mpg  
0            MANUAL         Coupe           26        19  
1            MANUAL   Convertible           28        19  
2            MANUAL         Coupe           28        20  
3            MANUAL         Coupe           28        18  
4            MANUAL   Convertible           28        18

# Split the data
Split your data in train/val/test sets with 60%/20%/20% distribution.
Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
Make sure that the target value (above_average) is not in your dataframe.

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
df_full_train, df_test = train_test_split(data, test_size=.2, random_state=1)

In [27]:
len(df_full_train), len (df_test)

(9531, 2383)

In [28]:
df_train, df_val = train_test_split(df_full_train, test_size=.25, random_state=1)

In [29]:
len(df_full_train), len (df_test), len(df_val)

(9531, 2383, 2383)

In [30]:
df_train

above_average        make              model  year  engine_hp  \
5727              1      Toyota  Highlander Hybrid  2016      280.0   
5814              0   Chevrolet     Impala Limited  2014      300.0   
8450              0       Buick              Regal  2016      259.0   
2396              1  Volkswagen                 CC  2015      280.0   
5494              0       Dodge      Grand Caravan  2016      283.0   
...             ...         ...                ...   ...        ...   
5864              0      Subaru            Impreza  2015      148.0   
7924              0    Infiniti               QX50  2016      325.0   
4719              0       Honda                Fit  2017      130.0   
63                0        Audi                200  1991      162.0   
7918              0    Infiniti                QX4  2003      240.0   

      engine_cylinders transmission_type      vehicle_style  highway_mpg  \
5727               6.0         AUTOMATIC            4dr SUV           28   
5814               6.0         AUTOMATIC              Sedan           30   
8450               4.0         AUTOMATIC              Sedan           27   
2396               6.0  AUTOMATED_MANUAL              Sedan           25   
5494               6.0         AUTOMATIC  Passenger Minivan           25   
...                ...               ...                ...          ...   
5864               4.0            MANUAL      4dr Hatchback           33   
7924               6.0         AUTOMATIC            4dr SUV           24   
4719               4.0         AUTOMATIC      4dr Hatchback           37   
63                 5.0         AUTOMATIC              Sedan           20   
7918               6.0         AUTOMATIC            4dr SUV           18   

      city_mpg  
5727        27  
5814        18  
8450        19  
2396        17  
5494        17  
...        ...  
5864        24  
7924        17  
4719        32  
63          16  
7918        14  

[7148 rows x 10 columns]

In [31]:
df_train =  df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val= df_val.reset_index(drop=True)

In [32]:
y_train = df_train.above_average.values
y_val = df_val.above_average.values
y_test = df_test.above_average.values

In [33]:
del df_train['above_average']

# Question 3
Calculate the mutual information score between above_average and other categorical variables in our dataset. Use the training set only.
Round the scores to 2 decimals using round(score, 2).
Which of these variables has the lowest mutual information score?

In [34]:
df_full_train = df_full_train.reset_index(drop=True)

In [35]:
df_full_train.above_average.value_counts()

0    6924
1    2607
Name: above_average, dtype: int64

In [36]:
df_full_train.above_average.value_counts(normalize=True)

0    0.726472
1    0.273528
Name: above_average, dtype: float64

In [37]:
global_score = df_full_train.above_average.mean()
round(global_score, 2)

0.27

In [39]:
from IPython.display import display

In [40]:
for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).above_average.agg(['mean' , 'count'])
    df_group ['diff'] = df_group['mean'] - global_score
    df_group ['risk'] = df_group['mean'] / global_score
    display(df_group)
    print()
    print()

make


mean  count      diff      risk
make                                              
Acura          0.374359    195  0.100830  1.368629
Alfa Romeo     1.000000      3  0.726472  3.655926
Aston Martin   1.000000     81  0.726472  3.655926
Audi           0.645756    271  0.372228  2.360838
BMW            0.808824    272  0.535295  2.956999
Bentley        1.000000     60  0.726472  3.655926
Bugatti        1.000000      2  0.726472  3.655926
Buick          0.097561    164 -0.175968  0.356676
Cadillac       0.871069    318  0.597541  3.184565
Chevrolet      0.176471    918 -0.097058  0.645163
Chrysler       0.091503    153 -0.182025  0.334529
Dodge          0.086694    496 -0.186835  0.316945
FIAT           0.000000     43 -0.273528  0.000000
Ferrari        1.000000     55  0.726472  3.655926
Ford           0.144718    691 -0.128811  0.529078
GMC            0.226933    401 -0.046596  0.829649
Genesis        1.000000      2  0.726472  3.655926
HUMMER         0.214286     14 -0.059243  0.783413
Honda          0.030220    364 -0.243309  0.110481
Hyundai        0.029536    237 -0.243993  0.107981
Infiniti       0.569853    272  0.296324  2.083340
Kia            0.069892    186 -0.203636  0.255522
Lamborghini    1.000000     41  0.726472  3.655926
Land Rover     0.775701    107  0.502172  2.835905
Lexus          0.593939    165  0.320411  2.171399
Lincoln        0.622047    127  0.348519  2.274159
Lotus          1.000000     26  0.726472  3.655926
Maserati       1.000000     49  0.726472  3.655926
Maybach        1.000000     14  0.726472  3.655926
Mazda          0.006231    321 -0.267298  0.022778
McLaren        1.000000      4  0.726472  3.655926
Mercedes-Benz  0.693950    281  0.420422  2.537031
Mitsubishi     0.000000    182 -0.273528  0.000000
Nissan         0.148889    450 -0.124640  0.544327
Oldsmobile     0.000000    124 -0.273528  0.000000
Plymouth       0.014085     71 -0.259444  0.051492
Pontiac        0.000000    149 -0.273528  0.000000
Porsche        0.893805    113  0.620277  3.267686
Rolls-Royce    1.000000     24  0.726472  3.655926
Saab           0.250000     84 -0.023528  0.913982
Scion          0.000000     46 -0.273528  0.000000
Spyker         1.000000      2  0.726472  3.655926
Subaru         0.000000    205 -0.273528  0.000000
Suzuki         0.000000    277 -0.273528  0.000000
Tesla          1.000000     15  0.726472  3.655926
Toyota         0.169179    597 -0.104349  0.618507
Volkswagen     0.047096    637 -0.226433  0.172179
Volvo          0.409910    222  0.136381  1.498600



model


mean  count      diff      risk
model                                          
1 Series    0.357143     14  0.083614  1.305688
1 Series M  1.000000      1  0.726472  3.655926
100         0.000000     13 -0.273528  0.000000
124 Spider  0.000000      3 -0.273528  0.000000
190-Class   0.000000      4 -0.273528  0.000000
...              ...    ...       ...       ...
iQ          0.000000      2 -0.273528  0.000000
tC          0.000000     12 -0.273528  0.000000
xA          0.000000      4 -0.273528  0.000000
xB          0.000000      8 -0.273528  0.000000
xD          0.000000      8 -0.273528  0.000000

[900 rows x 4 columns]



transmission_type


mean  count      diff      risk
transmission_type                                     
AUTOMATED_MANUAL   0.480159    504  0.206630  1.755425
AUTOMATIC          0.303840   6589  0.030311  1.110816
DIRECT_DRIVE       0.403509     57  0.129980  1.475198
MANUAL             0.143824   2364 -0.129704  0.525810
UNKNOWN            0.000000     17 -0.273528  0.000000



vehicle_style


mean  count      diff      risk
vehicle_style                                           
2dr Hatchback        0.000000    394 -0.273528  0.000000
2dr SUV              0.044248    113 -0.229281  0.161767
4dr Hatchback        0.041522    578 -0.232006  0.151803
4dr SUV              0.374494   1976  0.100965  1.369122
Cargo Minivan        0.000000     59 -0.273528  0.000000
Cargo Van            0.000000     74 -0.273528  0.000000
Convertible          0.549231    650  0.275702  2.007947
Convertible SUV      0.160000     25 -0.113528  0.584948
Coupe                0.474872    975  0.201343  1.736096
Crew Cab Pickup      0.330841    535  0.057313  1.209531
Extended Cab Pickup  0.057769    502 -0.215760  0.211199
Passenger Minivan    0.083333    324 -0.190195  0.304661
Passenger Van        0.077670    103 -0.195859  0.283955
Regular Cab Pickup   0.006116    327 -0.267412  0.022360
Sedan                0.286656   2428  0.013127  1.047992
Wagon                0.160256    468 -0.113272  0.585886

In [45]:
from sklearn.metrics import mutual_info_score

In [46]:
mutual_info_score(df_full_train.above_average, df_full_train.make)

0.23888341453006923

In [47]:
def mutual_info_above_average_score(series):
    return mutual_info_score(df_full_train.above_average, series)

In [48]:
mi = df_full_train[categorical].apply(mutual_info_above_average_score)
mi.sort_values(ascending = False)

model                0.461397
make                 0.238883
vehicle_style        0.082659
transmission_type    0.019411
dtype: float64

transmission_type    0.019411

# Question 4
Now let's train a logistic regression.
Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
Fit the model on the training dataset.
To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
Calculate the accuracy on the validation dataset and round it to 2 decimal digits.
What accuracy did you get?

# One-hot encoding

In [49]:
from sklearn.feature_extraction import DictVectorizer

In [50]:
dicts = df_train[['model','make','vehicle_style','transmission_type']].iloc[:10].to_dict(orient='records')

In [51]:
dv = DictVectorizer(sparse=False)

In [52]:
dv.fit(dicts)

DictVectorizer(sparse=False)

In [53]:
dv.transform(dicts)

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 

In [54]:
dv.get_feature_names_out()

array(['make=Buick', 'make=Chevrolet', 'make=Dodge', 'make=Ford',
       'make=Mazda', 'make=Nissan', 'make=Toyota', 'make=Volkswagen',
       'model=CC', 'model=CX-7', 'model=Golf GTI', 'model=Grand Caravan',
       'model=Highlander Hybrid', 'model=Impala Limited',
       'model=Pathfinder', 'model=Regal', 'model=Windstar',
       'transmission_type=AUTOMATED_MANUAL',
       'transmission_type=AUTOMATIC', 'transmission_type=MANUAL',
       'vehicle_style=4dr Hatchback', 'vehicle_style=4dr SUV',
       'vehicle_style=Passenger Minivan', 'vehicle_style=Sedan'],
      dtype=object)

In [55]:
numerical = ['year', 'engine_hp', 'engine_cylinders','highway_mpg', 'city_mpg']

In [56]:
df_train[categorical + numerical]

make              model transmission_type      vehicle_style  \
0         Toyota  Highlander Hybrid         AUTOMATIC            4dr SUV   
1      Chevrolet     Impala Limited         AUTOMATIC              Sedan   
2          Buick              Regal         AUTOMATIC              Sedan   
3     Volkswagen                 CC  AUTOMATED_MANUAL              Sedan   
4          Dodge      Grand Caravan         AUTOMATIC  Passenger Minivan   
...          ...                ...               ...                ...   
7143      Subaru            Impreza            MANUAL      4dr Hatchback   
7144    Infiniti               QX50         AUTOMATIC            4dr SUV   
7145       Honda                Fit         AUTOMATIC      4dr Hatchback   
7146        Audi                200         AUTOMATIC              Sedan   
7147    Infiniti                QX4         AUTOMATIC            4dr SUV   

      year  engine_hp  engine_cylinders  highway_mpg  city_mpg  
0     2016      280.0               6.0           28        27  
1     2014      300.0               6.0           30        18  
2     2016      259.0               4.0           27        19  
3     2015      280.0               6.0           25        17  
4     2016      283.0               6.0           25        17  
...    ...        ...               ...          ...       ...  
7143  2015      148.0               4.0           33        24  
7144  2016      325.0               6.0           24        17  
7145  2017      130.0               4.0           37        32  
7146  1991      162.0               5.0           20        16  
7147  2003      240.0               6.0           18        14  

[7148 rows x 9 columns]

In [63]:
train_dict = df_train[categorical + numerical].to_dict(orient='records')

In [58]:
train_dict[0]

{'make': 'Toyota',
 'model': 'Highlander Hybrid',
 'transmission_type': 'AUTOMATIC',
 'vehicle_style': '4dr SUV',
 'year': 2016,
 'engine_hp': 280.0,
 'engine_cylinders': 6.0,
 'highway_mpg': 28,
 'city_mpg': 27}

In [59]:
dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [60]:
X_train = dv.transform(train_dict)

In [61]:
X_train.shape

(7148, 954)

In [64]:
X_train = dv.transform(train_dict)

In [65]:
X_train.shape

(7148, 954)

In [66]:
dv.get_feature_names()

C:\Users\POLOO2\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['city_mpg',
 'engine_cylinders',
 'engine_hp',
 'highway_mpg',
 'make=Acura',
 'make=Alfa Romeo',
 'make=Aston Martin',
 'make=Audi',
 'make=BMW',
 'make=Bentley',
 'make=Bugatti',
 'make=Buick',
 'make=Cadillac',
 'make=Chevrolet',
 'make=Chrysler',
 'make=Dodge',
 'make=FIAT',
 'make=Ferrari',
 'make=Ford',
 'make=GMC',
 'make=Genesis',
 'make=HUMMER',
 'make=Honda',
 'make=Hyundai',
 'make=Infiniti',
 'make=Kia',
 'make=Lamborghini',
 'make=Land Rover',
 'make=Lexus',
 'make=Lincoln',
 'make=Lotus',
 'make=Maserati',
 'make=Maybach',
 'make=Mazda',
 'make=McLaren',
 'make=Mercedes-Benz',
 'make=Mitsubishi',
 'make=Nissan',
 'make=Oldsmobile',
 'make=Plymouth',
 'make=Pontiac',
 'make=Porsche',
 'make=Rolls-Royce',
 'make=Saab',
 'make=Scion',
 'make=Spyker',
 'make=Subaru',
 'make=Suzuki',
 'make=Tesla',
 'make=Toyota',
 'make=Volkswagen',
 'make=Volvo',
 'model=1 Series',
 'model=1 Series M',
 'model=100',
 'model=124 Spider',
 'model=190-Class',
 'model=2',
 'model=2 Series',
 'm

# Training logistic regression

In [67]:
from sklearn.linear_model import LogisticRegression

In [68]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [69]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [70]:
model.predict_proba(X_val)

array([[2.79875354e-01, 7.20124646e-01],
       [9.97674072e-01, 2.32592809e-03],
       [7.65430475e-01, 2.34569525e-01],
       ...,
       [9.97529417e-01, 2.47058282e-03],
       [3.11426230e-06, 9.99996886e-01],
       [9.55004037e-01, 4.49959628e-02]])

In [71]:
y_pred = model.predict_proba(X_val)[:, 1]

In [72]:
y_pred

array([0.72012465, 0.00232593, 0.23456952, ..., 0.00247058, 0.99999689,
       0.04499596])

In [73]:
above_average_decision = y_pred >average

In [74]:
(y_val == above_average_decision).mean()

0.7255560218212337

In [75]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = above_average_decision.astype(int)
df_pred['actual'] = y_val

In [76]:
df_pred

probability  prediction  actual
0        0.720125           0       1
1        0.002326           0       0
2        0.234570           0       0
3        0.070990           0       0
4        0.000011           0       0
...           ...         ...     ...
2378     0.936669           0       1
2379     0.010917           0       0
2380     0.002471           0       0
2381     0.999997           0       1
2382     0.044996           0       0

[2383 rows x 3 columns]

In [77]:
df_pred['correct'] = df_pred.prediction == df_pred.actual

In [78]:
df_pred

probability  prediction  actual  correct
0        0.720125           0       1    False
1        0.002326           0       0     True
2        0.234570           0       0     True
3        0.070990           0       0     True
4        0.000011           0       0     True
...           ...         ...     ...      ...
2378     0.936669           0       1    False
2379     0.010917           0       0     True
2380     0.002471           0       0     True
2381     0.999997           0       1    False
2382     0.044996           0       0     True

[2383 rows x 4 columns]

In [79]:
df_pred.correct.mean()

0.7255560218212337

In [81]:
pred_ini = df_pred.correct.mean()
pred_ini

0.7255560218212337

# Question 5
Let's find the least useful feature using the feature elimination technique.
Train a model with all these features (using the same parameters as in Q4).
Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
For each feature, calculate the difference between the original accuracy and the accuracy without the feature.
Which of following feature has the smallest difference?

In [82]:
dv.get_feature_names_out()

array(['city_mpg', 'engine_cylinders', 'engine_hp', 'highway_mpg',
       'make=Acura', 'make=Alfa Romeo', 'make=Aston Martin', 'make=Audi',
       'make=BMW', 'make=Bentley', 'make=Bugatti', 'make=Buick',
       'make=Cadillac', 'make=Chevrolet', 'make=Chrysler', 'make=Dodge',
       'make=FIAT', 'make=Ferrari', 'make=Ford', 'make=GMC',
       'make=Genesis', 'make=HUMMER', 'make=Honda', 'make=Hyundai',
       'make=Infiniti', 'make=Kia', 'make=Lamborghini', 'make=Land Rover',
       'make=Lexus', 'make=Lincoln', 'make=Lotus', 'make=Maserati',
       'make=Maybach', 'make=Mazda', 'make=McLaren', 'make=Mercedes-Benz',
       'make=Mitsubishi', 'make=Nissan', 'make=Oldsmobile',
       'make=Plymouth', 'make=Pontiac', 'make=Porsche',
       'make=Rolls-Royce', 'make=Saab', 'make=Scion', 'make=Spyker',
       'make=Subaru', 'make=Suzuki', 'make=Tesla', 'make=Toyota',
       'make=Volkswagen', 'make=Volvo', 'model=1 Series',
       'model=1 Series M', 'model=100', 'model=124 Spider',
     

In [83]:
model.coef_[0].round(3)

array([ 6.300e-02, -1.470e-01,  3.900e-02,  1.500e-02,  8.680e-01,
        9.700e-01,  4.570e-01,  3.019e+00,  2.324e+00,  1.240e-01,
        0.000e+00, -6.160e-01,  2.594e+00, -1.716e+00, -9.580e-01,
       -2.994e+00, -3.090e-01,  5.770e-01, -2.010e+00, -8.910e-01,
        2.280e-01, -6.000e-03, -1.389e+00, -2.702e+00,  2.160e-01,
       -1.718e+00,  5.000e-03,  2.146e+00,  1.556e+00,  1.455e+00,
        3.739e+00,  9.810e-01,  2.000e-03, -1.516e+00,  0.000e+00,
        6.630e-01, -1.537e+00, -1.357e+00, -1.167e+00, -1.340e-01,
       -2.848e+00,  1.722e+00,  8.490e-01,  1.014e+00, -1.800e-01,
        1.190e-01, -2.270e+00, -1.643e+00,  2.610e+00, -1.082e+00,
       -6.380e-01,  1.236e+00, -4.250e-01,  7.900e-02, -8.200e-02,
       -1.700e-02, -8.000e-03, -1.000e-03, -1.070e+00, -6.490e-01,
       -3.000e-03, -5.000e-03, -3.000e-03, -1.050e-01, -4.330e-01,
        3.790e-01,  3.840e-01, -3.480e-01, -1.190e-01, -1.500e-01,
       -1.450e-01, -0.000e+00, -6.000e-03, -1.093e+00,  4.520e

In [84]:
list(zip(dv.get_feature_names(), model.coef_[0].round(3)))

C:\Users\POLOO2\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


[('city_mpg', 0.063),
 ('engine_cylinders', -0.147),
 ('engine_hp', 0.039),
 ('highway_mpg', 0.015),
 ('make=Acura', 0.868),
 ('make=Alfa Romeo', 0.97),
 ('make=Aston Martin', 0.457),
 ('make=Audi', 3.019),
 ('make=BMW', 2.324),
 ('make=Bentley', 0.124),
 ('make=Bugatti', 0.0),
 ('make=Buick', -0.616),
 ('make=Cadillac', 2.594),
 ('make=Chevrolet', -1.716),
 ('make=Chrysler', -0.958),
 ('make=Dodge', -2.994),
 ('make=FIAT', -0.309),
 ('make=Ferrari', 0.577),
 ('make=Ford', -2.01),
 ('make=GMC', -0.891),
 ('make=Genesis', 0.228),
 ('make=HUMMER', -0.006),
 ('make=Honda', -1.389),
 ('make=Hyundai', -2.702),
 ('make=Infiniti', 0.216),
 ('make=Kia', -1.718),
 ('make=Lamborghini', 0.005),
 ('make=Land Rover', 2.146),
 ('make=Lexus', 1.556),
 ('make=Lincoln', 1.455),
 ('make=Lotus', 3.739),
 ('make=Maserati', 0.981),
 ('make=Maybach', 0.002),
 ('make=Mazda', -1.516),
 ('make=McLaren', 0.0),
 ('make=Mercedes-Benz', 0.663),
 ('make=Mitsubishi', -1.537),
 ('make=Nissan', -1.357),
 ('make=Oldsmo

# Iteration 1

In [85]:
subset = ['year', 'engine_hp', 'transmission_type','city_mpg']

In [91]:
df_train[subset].iloc[:10]

year  engine_hp transmission_type  city_mpg
0  2016      280.0         AUTOMATIC        27
1  2014      300.0         AUTOMATIC        18
2  2016      259.0         AUTOMATIC        19
3  2015      280.0  AUTOMATED_MANUAL        17
4  2016      283.0         AUTOMATIC        17
5  2015      260.0         AUTOMATIC        19
6  2017      220.0            MANUAL        24
7  2015      260.0         AUTOMATIC        19
8  2003      200.0         AUTOMATIC        16
9  2012      161.0         AUTOMATIC        20

In [92]:
train_dict_small = df_train[subset].to_dict(orient='records')
#train_val_small = df_val[subset].to_dict(orient='records')

dv_small = DictVectorizer(sparse=False)
dv_small.fit(train_dict_small)

X_small_train = dv_small.transform(train_dict_small)
#X_small_val = dv_small.transform(train_val_small)

dv_small.get_feature_names_out()

array(['city_mpg', 'engine_hp', 'transmission_type=AUTOMATED_MANUAL',
       'transmission_type=AUTOMATIC', 'transmission_type=DIRECT_DRIVE',
       'transmission_type=MANUAL', 'transmission_type=UNKNOWN', 'year'],
      dtype=object)

In [93]:
model_small = LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')
model_small.fit(X_small_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [94]:
model_small.intercept_[0]

-0.015457588816316134

In [95]:
model_small.coef_[0]

array([ 0.0765254 ,  0.02793229,  0.44089566,  0.25018613, -0.04207922,
       -0.6426538 , -0.02180637, -0.00503093])

In [96]:
dict(zip(dv_small.get_feature_names(), model_small.coef_[0].round(3)))

C:\Users\POLOO2\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


{'city_mpg': 0.077,
 'engine_hp': 0.028,
 'transmission_type=AUTOMATED_MANUAL': 0.441,
 'transmission_type=AUTOMATIC': 0.25,
 'transmission_type=DIRECT_DRIVE': -0.042,
 'transmission_type=MANUAL': -0.643,
 'transmission_type=UNKNOWN': -0.022,
 'year': -0.005}

In [111]:
val_dict_small = df_val[subset].to_dict(orient='records')
X_small_val = dv_small.transform(val_dict_small)

In [113]:
y_pred_small = model_small.predict_proba(X_small_val)[:, 1]

In [112]:
y_pred_small

array([0.79045723, 0.39367285, 0.30510546, ..., 0.03988061, 0.99909472,
       0.32820276])

In [114]:
above_average_decision_small = y_pred_small >average

In [115]:
(y_val == above_average_decision_small).mean()

0.7255560218212337

In [116]:
df_pred_small = pd.DataFrame()
df_pred_small['probability'] = y_pred_small
df_pred_small['prediction'] = above_average_decision_small.astype(int)
df_pred_small['actual'] = y_val

In [117]:
df_pred_small

probability  prediction  actual
0        0.790457           0       1
1        0.393673           0       0
2        0.305105           0       0
3        0.305581           0       0
4        0.004058           0       0
...           ...         ...     ...
2378     0.958037           0       1
2379     0.340133           0       0
2380     0.039881           0       0
2381     0.999095           0       1
2382     0.328203           0       0

[2383 rows x 3 columns]

In [104]:
df_pred_small['correct'] = df_pred_small.prediction == df_pred_small.actual

In [106]:
df_pred_small.correct.mean()

0.7255560218212337

In [107]:
pred_iter1 =  df_pred_small.correct.mean()

In [110]:
dif1 = (pred_iter1-pred_ini).round(6)
dif1

0.0

# Iteration 2

In [118]:
subset2 = ['year', 'engine_hp', 'transmission_type']

In [119]:
df_train[subset2].iloc[:10]

year  engine_hp transmission_type
0  2016      280.0         AUTOMATIC
1  2014      300.0         AUTOMATIC
2  2016      259.0         AUTOMATIC
3  2015      280.0  AUTOMATED_MANUAL
4  2016      283.0         AUTOMATIC
5  2015      260.0         AUTOMATIC
6  2017      220.0            MANUAL
7  2015      260.0         AUTOMATIC
8  2003      200.0         AUTOMATIC
9  2012      161.0         AUTOMATIC

In [120]:
train_dict_small_2 = df_train[subset2].to_dict(orient='records')
train_val_small_2 = df_val[subset2].to_dict(orient='records')

dv_small_2 = DictVectorizer(sparse=False)
dv_small_2.fit(train_dict_small)

X_small_train_2 = dv_small.transform(train_dict_small_2)
X_small_val_2 = dv_small.transform(train_val_small_2)

dv_small_2.get_feature_names_out()

array(['city_mpg', 'engine_hp', 'transmission_type=AUTOMATED_MANUAL',
       'transmission_type=AUTOMATIC', 'transmission_type=DIRECT_DRIVE',
       'transmission_type=MANUAL', 'transmission_type=UNKNOWN', 'year'],
      dtype=object)

In [121]:
model_small_2 = LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')
model_small_2.fit(X_small_train_2, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [122]:
model_small_2.intercept_[0]

-0.021427843445434497

In [123]:
model_small_2.coef_[0]

array([ 0.        ,  0.02402934,  0.48058304,  0.0070514 ,  0.32652576,
       -0.80972986, -0.02585818, -0.00367122])

In [124]:
dict(zip(dv_small_2.get_feature_names(), model_small_2.coef_[0].round(3)))

C:\Users\POLOO2\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


{'city_mpg': 0.0,
 'engine_hp': 0.024,
 'transmission_type=AUTOMATED_MANUAL': 0.481,
 'transmission_type=AUTOMATIC': 0.007,
 'transmission_type=DIRECT_DRIVE': 0.327,
 'transmission_type=MANUAL': -0.81,
 'transmission_type=UNKNOWN': -0.026,
 'year': -0.004}

In [125]:
y_pred_small_2 = model_small_2.predict_proba(X_small_val_2)[:, 1]

In [126]:
y_pred_small_2

array([0.73073915, 0.48480826, 0.29903791, ..., 0.0439705 , 0.99800027,
       0.40863107])

In [127]:
above_average_decision_small_2 = y_pred_small_2 >average

In [129]:
(y_val == above_average_decision_small_2).mean()

0.7255560218212337

# Iteration 3

# Question 6
For this question, we'll see how to use a linear regression model from Scikit-Learn.
We'll need to use the original column price. Apply the logarithmic transformation to this column.
Fit the Ridge regression model on the training data with a solver 'sag'. Set the seed to 42.
This model also has a parameter alpha. Let's try the following values: [0, 0.01, 0.1, 1, 10].
Round your RMSE scores to 3 decimal digits.
Which of these alphas leads to the best RMSE on the validation set?

In [11]:
mean_bedrooms = data['total_bedrooms'].mean()
mean_bedrooms

537.8705525375618

In [12]:
data['total_bedrooms'].fillna(mean_bedrooms).mean()

537.8705525375639

# No, it's left the same.

# Question 7
Select all the options located on islands.
Select only columns housing_median_age, total_rooms, total_bedrooms.
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [950, 1300, 800, 1000, 1300].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the last element of w?

In [13]:
island_df = data[data.ocean_proximity == 'ISLAND']
island_df = island_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
island_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [14]:
X = island_df.values
XTX = X.T.dot(X)

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [15]:
y = np.array([950, 1300, 800, 1000, 1300])

In [16]:
w = (XTX_inv @ X.T) @ y

In [17]:
w


array([23.12330961, -1.48124183,  5.69922946])

In [18]:
w[2]

5.6992294550655656

# Note: we just implemented normal equation

We'll talk about it more in the next week (Machine Learning for Regression)